### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by JIElite** [nailo2c/pysc2-tutorial#1]
Environment:
Python3.5

根據 README.md 的指令執行兩種 agent 會發生錯誤。以下分別是執行 scripted agent 以及 dqn agent 的錯誤:
- scripted agent
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/chenjiehan/starcraft2/sc2env/lib/python3.5/site-packages/pysc2/bin/agent.py", line 112, in <module>
    app.run(main)
  File "/Users/chenjiehan/starcraft2/sc2env/lib/python3.5/site-packages/absl/app.py", line 262, in run
    _run_main(main, argv)
  File "/Users/chenjiehan/starcraft2/sc2env/lib/python3.5/site-packages/absl/app.py", line 227, in _run_main
    sys.exit(main(argv))
  File "/Users/chenjiehan/starcraft2/sc2env/lib/python3.5/site-packages/pysc2/bin/agent.py", line 98, in main
    run_thread(agent_cls, FLAGS.map, FLAGS.render)
  File "/Users/chenjiehan/starcraft2/sc2env/lib/python3.5/site-packages/pysc2/bin/agent.py", line 77, in run_thread
    run_loop.run_loop([agent], env, FLAGS.max_agent_steps)
  File "/Users/chenjiehan/starcraft2/sc2env/lib/python3.5/site-packages/pysc2/env/run_loop.py", line 41, in run_loop
    for agent, timestep in zip(agents, timesteps)]
  File "/Users/chenjiehan/starcraft2/sc2env/lib/python3.5/site-packages/pysc2/env/run_loop.py", line 41, in <listcomp>
    for agent, timestep in zip(agents, timesteps)]
  File "/Users/chenjiehan/starcraft2/nailo2c/pysc2-tutorial/scripted_agent/simple_agent_protoss.py", line 101, in step
    target = self.transformLocation(int(pylon_x.mean()), 10, int(pylon_y.mean()), 0)
ValueError: cannot convert float NaN to integer
I1017 00:20:27.772028 140736507827136 sc2_env.py:327] Environment Close
I1017 00:20:27.772258 140736507827136 sc2_env.py:342] 
I1017 00:20:27.772341 140736507827136 sc2_env.py:327] Environment Close
I1017 00:20:27.772413 140736507827136 sc2_env.py:342] 
W1017 00:20:30.964193 140736507827136 sc_process.py:183] Killing the process.
I1017 00:20:31.131977 140736507827136 sc_process.py:166] Shutdown with return code: -9
```

- dqn agent
```
Traceback (most recent call last):
  File "dqn_agent/train_mineral_shards.py", line 52, in <module>
    main()
  File "dqn_agent/train_mineral_shards.py", line 25, in main
    with sc2_env.SC2Env(map_name="CollectMineralShards", step_mul=step_mul) as env:
  File "/Users/chenjiehan/starcraft2/sc2env/lib/python3.5/site-packages/pysc2/env/sc2_env.py", line 132, in __init__
    self._setup((agent_race, bot_race, difficulty), **kwargs)
  File "/Users/chenjiehan/starcraft2/sc2env/lib/python3.5/site-packages/pysc2/env/sc2_env.py", line 173, in _setup
    self._run_config = run_configs.get()
  File "/Users/chenjiehan/starcraft2/sc2env/lib/python3.5/site-packages/pysc2/run_configs/__init__.py", line 38, in get
    if FLAGS.sc2_run_config is None:  # Find the highest priority as default.
  File "/Users/chenjiehan/starcraft2/sc2env/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 509, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --sc2_run_config before flags were parsed.
```
請問您有遇到過這樣的錯誤訊息嗎？應該怎麼處理？

**Comment by aaron-y-chen** [comment]
第一個問題是那個scripted agent寫太多hardcode的東西，我擷取各個單位&建築的資訊很仰賴screen畫面。因此如果遊戲一打開，你就把畫面移走，code就偵測不到單位的資訊，就會產生你提出的那個error。總之第一個code很呆，遊戲打開後不要移動遊戲畫面，理論上就能順利地跑下去。

第二個問題一時想不到解法，要不要嘗試將python跟gflags都update到最新？

**Comment by yilei** [comment]
第二個問題：把 `import gflags as flags` 換成 `from absl import flags` 應該就可以了，參見 https://github.com/deepmind/pysc2/commit/f2f96c08c32ea92fa60485cc6d7307bc17c1c6db

**Comment by aaron-y-chen** [comment]
Excellent work! Thanks :D

**Comment by JIElite** [comment]
@yilei  Thank you! it works!
